name: Test
on:
  push:
    branches:
      - main
      - $default-branch
  pull_request:
    branches:
      - main
      - $default-branch
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run eslint
      - run: pnpm run test:ci
      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy-docs:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build:pack
      - name: Generate docs
        run: pnpm run docs
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: docs
